# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-latest"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "fedora-docker"
    vb.memory = "2048"
    vb.cpus = 2
    vb.customize ["modifyvm",:id,"--groups","/Fedora"]
  end
  config.vm.hostname="fedora-docker"
  config.vm.network "forwarded_port", guest: 8888, host: 18888
  config.vm.network "private_network", ip: "192.168.5.20"
  config.vm.synced_folder ".", "/home/vagrant/data"
  config.vm.provision "shell", path: "pro.sh", privileged: true
end
